-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tb_sys_setup
(
    sys_setup_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    modified_on timestamp without time zone NOT NULL,
    modified_by character varying(255) NOT NULL,
    sys_desc character varying(50),
    sys_url text,
    is_in_use integer,
    PRIMARY KEY (sys_setup_id)
);

CREATE TABLE IF NOT EXISTS public.tb_co
(
    co_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    modified_on timestamp without time zone NOT NULL,
    modified_by character varying(255) NOT NULL,
    co_code character varying(50) NOT NULL,
    co_desc character varying(255) NOT NULL,
    tin_num character varying(14),
    register_num character varying(20),
    sst_num character varying(35),
    ttx_num character varying(17) NOT NULL,
    email character varying(320),
    misc_code character varying(5),
    misc_desc character varying(300),
    addr_line_1 character varying(150),
    addr_line_2 character varying(150),
    addr_line_3 character varying(150),
    post_code character varying(50),
    city character varying(50),
    state character varying(50),
    country character varying(3),
    contact_number character varying(20),
    PRIMARY KEY (co_id)
);

CREATE TABLE IF NOT EXISTS public.tb_state
(
    state_code character varying(5) NOT NULL,
    state_desc character varying(255),
    PRIMARY KEY (city_id)
);

COMMENT ON TABLE public.tb_state
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/state-codes/';

CREATE TABLE IF NOT EXISTS public.tb_country
(
    country_code character varying(5) NOT NULL,
    country_desc character varying(255),
    PRIMARY KEY (country_id)
);

COMMENT ON TABLE public.tb_country
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/countries/';

CREATE TABLE IF NOT EXISTS public.tb_user
(
    user_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    modified_on timestamp without time zone NOT NULL,
    modified_by character varying(255) NOT NULL,
    user_group_id integer NOT NULL,
    user_name character varying(255) NOT NULL,
    login_id character varying(255) NOT NULL,
    email character varying(255),
    pwd text,
    is_active integer,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.tb_user_group
(
    user_group_id serial NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    modified_on timestamp without time zone NOT NULL,
    modified_by character varying(255) NOT NULL,
    user_group_desc character varying(255),
    is_in_use integer,
    display_seq character varying(6),
    PRIMARY KEY (user_group_id)
);

CREATE TABLE IF NOT EXISTS public.tb_action
(
    action_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    action_code character varying(255),
    action_desc character varying(255),
    group_code character varying(255),
    is_in_use integer,
    is_default_func integer,
    allow_notif integer,
    PRIMARY KEY (action_id)
);

CREATE TABLE IF NOT EXISTS public.tb_action_param
(
    action_param_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    action_id uuid,
    action_param character varying(255),
    data_type character varying(50),
    data_length character varying(50),
    seq integer,
    is_compulsory integer,
    PRIMARY KEY (action_param_id)
);

CREATE TABLE IF NOT EXISTS public.tb_last_id
(
    last_id uuid NOT NULL,
    last_desc character varying(255),
    last_value character varying(255),
    PRIMARY KEY (last_id)
);

CREATE TABLE IF NOT EXISTS public.tb_trans
(
    trans_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    inv_type_code character varying(5),
    inv_num character varying(50),
    lhdn_inv_num character varying(50),
    amt numeric(15, 2),
    status character varying(20),
    PRIMARY KEY (trans_id)
);

CREATE TABLE IF NOT EXISTS public.tb_classification_code
(
    classification_code character varying NOT NULL,
    classification_desc text,
    PRIMARY KEY (classification_id, classification_code)
);

COMMENT ON TABLE public.tb_classification_code
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/classification-codes/';

CREATE TABLE IF NOT EXISTS public.tb_currency_code
(
    currency_code character varying(10) NOT NULL,
    currency_code_desc character varying(255),
    PRIMARY KEY (currency_code_id, currency_code)
);

COMMENT ON TABLE public.tb_currency_code
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/currencies/';

CREATE TABLE IF NOT EXISTS public.tb_msic_code
(
    msic_code character varying(5) NOT NULL,
    msic_desc character varying(300),
    msic_category_ref character varying(5),
    PRIMARY KEY (msic_code)
);

COMMENT ON TABLE public.tb_msic_code
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/msic-codes/';

CREATE TABLE IF NOT EXISTS public.tb_pymt_mode
(
    pymt_mode_code character varying(5) NOT NULL,
    pymt_mode_desc character varying(255),
    PRIMARY KEY (pymt_mode_code)
);

CREATE TABLE IF NOT EXISTS public.tb_invoice_type
(
    invoice_type_code character varying(5) NOT NULL,
    invoice_type_desc character varying(255),
    PRIMARY KEY (invoice_type_code)
);

COMMENT ON TABLE public.tb_invoice_type
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/e-invoice-types/';

CREATE TABLE IF NOT EXISTS public.tb_uom
(
    uom_code character varying(5) NOT NULL,
    uom_desc text,
    PRIMARY KEY (uom_code)
);

COMMENT ON TABLE public.tb_uom
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/unit-types/';

CREATE TABLE IF NOT EXISTS public.tb_tax_type
(
    tax_type_code character varying(5) NOT NULL,
    tax_type_desc character varying(255),
    PRIMARY KEY (tax_type_code)
);

COMMENT ON TABLE public.tb_tax_type
    IS 'refer to: https://sdk.myinvois.hasil.gov.my/codes/tax-types/';

CREATE TABLE IF NOT EXISTS public.tb_user_group_action
(
    user_group_action_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    user_group_id integer,
    action_id uuid,
    PRIMARY KEY (user_group_action_id)
);

CREATE TABLE IF NOT EXISTS public.tb_log
(
)
;

CREATE TABLE IF NOT EXISTS public.tb_uacc_log
(
    user_access_log_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    login_id character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    user_group_id uuid,
    sess_id uuid,
    status_id integer,
    user_host character varying(255),
    user_agent character varying(255),
    last_access_on timestamp without time zone,
    logout_on timestamp without time zone,
    browser_name character varying(255),
    os_platform character varying(255),
    browser_version character varying(255),
    PRIMARY KEY (user_access_log_id)
);

CREATE TABLE IF NOT EXISTS public.tb_user_status
(
    user_status_id integer NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    user_status_desc character varying(255) NOT NULL,
    allow_login integer,
    is_in_use integer,
    PRIMARY KEY (user_status_id)
);

CREATE TABLE IF NOT EXISTS public.tb_user_suspend_log
(
    user_suspend_log_id uuid NOT NULL,
    created_on timestamp without time zone NOT NULL,
    created_by character varying NOT NULL,
    user_id uuid NOT NULL,
    ban_time timestamp without time zone NOT NULL,
    PRIMARY KEY (user_suspend_log_id)
);

ALTER TABLE IF EXISTS public.tb_action_param
    ADD FOREIGN KEY (action_id)
    REFERENCES public.tb_action (action_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;